USE TiendaWebOrigen;
GO

TRUNCATE TABLE dbo.Resenas;
GO

INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0001', 'C007', 'P016', '2024-10-23', N'Producto llegó rápido y funciona perfecto. Muy recomendable.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0002', 'C028', 'P005', '2024-10-15', N'Gran relación calidad-precio. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0003', 'C035', 'P020', '2025-02-02', N'Entrega correcta, sin comentarios adicionales. OK.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0004', 'C021', 'P009', '2025-04-24', N'Producto recibido, cumple su función. OK.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0005', 'C030', 'P008', '2025-03-25', N'No cumple con lo anunciado, insatisfecho. No volvería a comprar.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0006', 'C021', 'P016', '2025-03-16', N'Muy satisfecho con la compra, lo recomiendo. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0007', 'C018', 'P011', '2024-12-03', N'Es lo que esperaba, nada excepcional. OK.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0008', 'C013', 'P017', '2025-01-06', N'Calidad superior, muy contento. Muy recomendable.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0009', 'C031', 'P008', '2025-01-27', N'No cumple con lo anunciado, insatisfecho. No volvería a comprar.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0010', 'C019', 'P003', '2025-04-10', N'Muy satisfecho con la compra, lo recomiendo. Muy recomendable.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0011', 'C031', 'P012', '2025-02-08', N'Envío tardío y producto dañado. No volvería a comprar.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0012', 'C023', 'P011', '2025-04-10', N'Es lo que esperaba, nada excepcional. OK.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0013', 'C008', 'P008', '2025-07-14', N'Es lo que esperaba, nada excepcional. OK.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0014', 'C013', 'P006', '2025-04-25', N'Calidad superior, muy contento. Muy recomendable.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0015', 'C039', 'P017', '2025-06-06', N'Me encanta este producto, excelente calidad. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0016', 'C024', 'P008', '2024-09-16', N'Me encanta este producto, excelente calidad. Muy recomendable.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0017', 'C018', 'P005', '2024-12-04', N'Me encanta este producto, excelente calidad. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0018', 'C032', 'P005', '2024-11-24', N'Me encanta este producto, excelente calidad. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0019', 'C031', 'P016', '2025-08-18', N'Muy satisfecho con la compra, lo recomiendo. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0020', 'C008', 'P016', '2025-01-05', N'Entrega correcta, sin comentarios adicionales. OK.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0021', 'C004', 'P019', '2025-04-11', N'Gran relación calidad-precio. Muy recomendable.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0022', 'C008', 'P008', '2024-11-07', N'No cumple con lo anunciado, insatisfecho. No volvería a comprar.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0023', 'C015', 'P020', '2025-01-26', N'Entrega correcta, sin comentarios adicionales. OK.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0024', 'C038', 'P010', '2024-11-26', N'Es lo que esperaba, nada excepcional. OK.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0025', 'C040', 'P002', '2025-05-30', N'Producto recibido, cumple su función. OK.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0026', 'C006', 'P009', '2024-12-05', N'Muy satisfecho con la compra, lo recomiendo. Muy recomendable.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0027', 'C001', 'P006', '2025-01-16', N'Gran relación calidad-precio. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0028', 'C015', 'P002', '2024-09-19', N'Producto llegó rápido y funciona perfecto. Muy recomendable.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0029', 'C015', 'P003', '2024-10-10', N'Satisface lo básico. OK.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0030', 'C008', 'P014', '2025-04-30', N'No funciona como esperaba, decepcionado. No volvería a comprar.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0031', 'C004', 'P003', '2024-11-13', N'Producto llegó rápido y funciona perfecto. Muy recomendable.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0032', 'C029', 'P010', '2024-09-20', N'Producto llegó rápido y funciona perfecto. Muy recomendable.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0033', 'C033', 'P009', '2025-08-03', N'No cumple con lo anunciado, insatisfecho. No volvería a comprar.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0034', 'C028', 'P002', '2025-05-08', N'Satisface lo básico. OK.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0035', 'C015', 'P003', '2024-11-17', N'Satisface lo básico. OK.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0036', 'C037', 'P009', '2025-01-16', N'Muy satisfecho con la compra, lo recomiendo. Muy recomendable.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0037', 'C018', 'P015', '2025-02-02', N'Gran relación calidad-precio. Muy recomendable.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0038', 'C031', 'P003', '2025-04-02', N'Producto llegó rápido y funciona perfecto. Muy recomendable.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0039', 'C022', 'P006', '2025-04-19', N'Calidad superior, muy contento. Muy recomendable.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0040', 'C003', 'P018', '2025-05-07', N'Envío tardío y producto dañado. No volvería a comprar.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0041', 'C026', 'P004', '2024-10-12', N'Producto recibido, cumple su función. OK.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0042', 'C027', 'P015', '2025-03-12', N'Gran relación calidad-precio. Muy recomendable.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0043', 'C029', 'P016', '2025-04-30', N'Información suficiente, sin mayor novedad. OK.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0044', 'C019', 'P005', '2025-07-13', N'Calidad superior, muy contento. Muy recomendable.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0045', 'C016', 'P020', '2024-12-05', N'Es lo que esperaba, nada excepcional. OK.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0046', 'C027', 'P018', '2025-01-20', N'Me encanta este producto, excelente calidad. Muy recomendable.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0047', 'C032', 'P005', '2024-12-27', N'Es lo que esperaba, nada excepcional. OK.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0048', 'C031', 'P014', '2025-01-23', N'Información suficiente, sin mayor novedad. OK.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0049', 'C025', 'P005', '2024-12-27', N'Gran relación calidad-precio. Muy recomendable.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0050', 'C018', 'P003', '2025-03-23', N'Entrega correcta, sin comentarios adicionales. OK.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0051', 'C001', 'P009', '2024-11-17', N'Producto llegó rápido y funciona perfecto. Muy recomendable.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0052', 'C010', 'P016', '2025-03-21', N'Calidad superior, muy contento. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0053', 'C035', 'P018', '2025-06-09', N'Producto llegó rápido y funciona perfecto. Muy recomendable.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0054', 'C025', 'P019', '2025-08-22', N'Calidad superior, muy contento. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0055', 'C025', 'P016', '2025-01-03', N'Muy satisfecho con la compra, lo recomiendo. Muy recomendable.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0056', 'C033', 'P005', '2025-07-24', N'Es lo que esperaba, nada excepcional. OK.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0057', 'C034', 'P004', '2025-07-02', N'Producto recibido, cumple su función. OK.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0058', 'C005', 'P005', '2025-03-24', N'Envío tardío y producto dañado. No volvería a comprar.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0059', 'C006', 'P013', '2025-03-03', N'Satisface lo básico. OK.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0060', 'C035', 'P016', '2025-05-16', N'Me encanta este producto, excelente calidad. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0061', 'C006', 'P008', '2024-10-24', N'Me encanta este producto, excelente calidad. Muy recomendable.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0062', 'C011', 'P015', '2025-08-21', N'Muy mala calidad, se rompió rápido. No volvería a comprar.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0063', 'C019', 'P002', '2025-07-01', N'Calidad superior, muy contento. Muy recomendable.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0064', 'C027', 'P017', '2025-06-18', N'No funciona como esperaba, decepcionado. No volvería a comprar.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0065', 'C040', 'P003', '2024-09-29', N'Satisface lo básico. OK.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0066', 'C038', 'P016', '2024-10-22', N'Calidad superior, muy contento. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0067', 'C017', 'P015', '2025-04-19', N'No cumple con lo anunciado, insatisfecho. No volvería a comprar.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0068', 'C005', 'P006', '2024-11-17', N'Producto llegó rápido y funciona perfecto. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0069', 'C017', 'P014', '2025-06-04', N'Envío tardío y producto dañado. No volvería a comprar.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0070', 'C007', 'P016', '2025-03-14', N'Gran relación calidad-precio. Muy recomendable.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0071', 'C019', 'P010', '2025-04-26', N'Calidad superior, muy contento. Muy recomendable.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0072', 'C004', 'P019', '2025-04-20', N'Entrega correcta, sin comentarios adicionales. OK.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0073', 'C023', 'P020', '2024-10-31', N'Muy satisfecho con la compra, lo recomiendo. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0074', 'C007', 'P005', '2025-04-08', N'Producto recibido, cumple su función. OK.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0075', 'C038', 'P002', '2025-07-29', N'Muy satisfecho con la compra, lo recomiendo. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0076', 'C027', 'P011', '2024-12-11', N'Muy satisfecho con la compra, lo recomiendo. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0077', 'C033', 'P017', '2025-05-05', N'Información suficiente, sin mayor novedad. OK.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0078', 'C022', 'P010', '2025-08-06', N'Entrega correcta, sin comentarios adicionales. OK.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0079', 'C026', 'P008', '2025-03-10', N'Satisface lo básico. OK.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0080', 'C001', 'P013', '2025-01-24', N'Me encanta este producto, excelente calidad. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0081', 'C038', 'P009', '2025-07-20', N'Producto llegó rápido y funciona perfecto. Muy recomendable.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0082', 'C002', 'P016', '2025-03-30', N'Pésima atención al cliente. No volvería a comprar.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0083', 'C005', 'P008', '2024-09-20', N'No cumple con lo anunciado, insatisfecho. No volvería a comprar.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0084', 'C008', 'P014', '2025-04-11', N'Me encanta este producto, excelente calidad. Muy recomendable.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0085', 'C007', 'P004', '2025-07-06', N'Gran relación calidad-precio. Muy recomendable.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0086', 'C024', 'P015', '2025-02-11', N'Pésima atención al cliente. No volvería a comprar.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0087', 'C027', 'P005', '2024-11-02', N'No cumple con lo anunciado, insatisfecho. No volvería a comprar.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0088', 'C003', 'P009', '2025-01-29', N'No funciona como esperaba, decepcionado. No volvería a comprar.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0089', 'C024', 'P008', '2024-12-09', N'Producto llegó rápido y funciona perfecto. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0090', 'C026', 'P002', '2025-01-24', N'Me encanta este producto, excelente calidad. Muy recomendable.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0091', 'C039', 'P007', '2025-03-27', N'Producto recibido, cumple su función. OK.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0092', 'C037', 'P005', '2025-05-30', N'Gran relación calidad-precio. Muy recomendable.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0093', 'C015', 'P007', '2024-11-12', N'Muy satisfecho con la compra, lo recomiendo. Muy recomendable.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0094', 'C010', 'P009', '2025-05-08', N'Satisface lo básico. OK.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0095', 'C002', 'P004', '2025-05-15', N'Producto llegó rápido y funciona perfecto. Muy recomendable.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0096', 'C002', 'P011', '2025-07-11', N'Me encanta este producto, excelente calidad. Muy recomendable.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0097', 'C008', 'P017', '2025-01-27', N'Entrega correcta, sin comentarios adicionales. OK.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0098', 'C038', 'P017', '2025-05-23', N'Gran relación calidad-precio. Muy recomendable.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0099', 'C034', 'P002', '2025-08-13', N'Me encanta este producto, excelente calidad. Muy recomendable.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0100', 'C028', 'P013', '2024-09-14', N'No cumple con lo anunciado, insatisfecho. No volvería a comprar.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0101', 'C006', 'P003', '2025-08-11', N'Muy satisfecho con la compra, lo recomiendo. Muy recomendable.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0102', 'C040', 'P009', '2024-09-14', N'Pésima atención al cliente. No volvería a comprar.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0103', 'C039', 'P013', '2024-12-29', N'No cumple con lo anunciado, insatisfecho. No volvería a comprar.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0104', 'C007', 'P014', '2024-10-13', N'Producto recibido, cumple su función. OK.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0105', 'C028', 'P007', '2025-02-14', N'No funciona como esperaba, decepcionado. No volvería a comprar.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0106', 'C026', 'P015', '2025-04-06', N'Me encanta este producto, excelente calidad. Muy recomendable.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0107', 'C017', 'P011', '2024-09-27', N'Muy satisfecho con la compra, lo recomiendo. Muy recomendable.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0108', 'C006', 'P003', '2025-02-04', N'Producto recibido, cumple su función. OK.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0109', 'C009', 'P012', '2024-11-30', N'Pésima atención al cliente. No volvería a comprar.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0110', 'C008', 'P011', '2025-08-18', N'Calidad superior, muy contento. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0111', 'C020', 'P020', '2024-12-28', N'Gran relación calidad-precio. Muy recomendable.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0112', 'C031', 'P005', '2025-03-18', N'Me encanta este producto, excelente calidad. Muy recomendable.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0113', 'C008', 'P012', '2025-05-21', N'Satisface lo básico. OK.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0114', 'C040', 'P018', '2025-08-31', N'Pésima atención al cliente. No volvería a comprar.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0115', 'C002', 'P009', '2025-03-24', N'Producto llegó rápido y funciona perfecto. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0116', 'C012', 'P001', '2024-10-12', N'Satisface lo básico. OK.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0117', 'C010', 'P003', '2025-07-29', N'Producto recibido, cumple su función. OK.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0118', 'C025', 'P007', '2025-06-25', N'Producto llegó rápido y funciona perfecto. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0119', 'C021', 'P010', '2024-11-12', N'Satisface lo básico. OK.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0120', 'C010', 'P002', '2025-08-19', N'Gran relación calidad-precio. Muy recomendable.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0121', 'C029', 'P009', '2024-11-07', N'No cumple con lo anunciado, insatisfecho. No volvería a comprar.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0122', 'C018', 'P014', '2025-07-17', N'Gran relación calidad-precio. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0123', 'C008', 'P014', '2025-01-07', N'Gran relación calidad-precio. Muy recomendable.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0124', 'C003', 'P010', '2025-08-16', N'Gran relación calidad-precio. Muy recomendable.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0125', 'C020', 'P007', '2025-05-06', N'Información suficiente, sin mayor novedad. OK.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0126', 'C008', 'P011', '2025-06-16', N'Calidad superior, muy contento. Muy recomendable.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0127', 'C035', 'P013', '2024-12-01', N'Satisface lo básico. OK.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0128', 'C026', 'P003', '2025-02-02', N'Producto recibido, cumple su función. OK.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0129', 'C005', 'P015', '2025-02-06', N'Satisface lo básico. OK.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0130', 'C027', 'P013', '2025-09-03', N'Calidad superior, muy contento. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0131', 'C040', 'P006', '2025-07-30', N'Envío tardío y producto dañado. No volvería a comprar.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0132', 'C016', 'P004', '2024-12-19', N'Calidad superior, muy contento. Muy recomendable.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0133', 'C020', 'P013', '2025-03-27', N'Información suficiente, sin mayor novedad. OK.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0134', 'C033', 'P003', '2024-12-26', N'Pésima atención al cliente. No volvería a comprar.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0135', 'C023', 'P012', '2025-05-16', N'Información suficiente, sin mayor novedad. OK.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0136', 'C017', 'P005', '2025-06-27', N'Gran relación calidad-precio. Muy recomendable.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0137', 'C032', 'P006', '2024-11-21', N'Pésima atención al cliente. No volvería a comprar.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0138', 'C040', 'P019', '2025-06-28', N'Producto llegó rápido y funciona perfecto. Muy recomendable.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0139', 'C031', 'P003', '2025-04-26', N'Producto llegó rápido y funciona perfecto. Muy recomendable.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0140', 'C023', 'P002', '2025-01-20', N'Envío tardío y producto dañado. No volvería a comprar.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0141', 'C004', 'P002', '2025-08-05', N'Producto llegó rápido y funciona perfecto. Muy recomendable.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0142', 'C039', 'P020', '2024-11-20', N'No cumple con lo anunciado, insatisfecho. No volvería a comprar.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0143', 'C029', 'P002', '2024-10-15', N'Satisface lo básico. OK.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0144', 'C039', 'P011', '2025-08-13', N'No funciona como esperaba, decepcionado. No volvería a comprar.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0145', 'C022', 'P004', '2024-12-29', N'Producto recibido, cumple su función. OK.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0146', 'C016', 'P002', '2024-12-19', N'Entrega correcta, sin comentarios adicionales. OK.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0147', 'C011', 'P020', '2025-02-27', N'Producto llegó rápido y funciona perfecto. Muy recomendable.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0148', 'C039', 'P011', '2025-08-11', N'Producto llegó rápido y funciona perfecto. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0149', 'C036', 'P004', '2025-05-07', N'Envío tardío y producto dañado. No volvería a comprar.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0150', 'C022', 'P005', '2025-03-18', N'Muy satisfecho con la compra, lo recomiendo. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0151', 'C009', 'P013', '2025-04-08', N'Muy mala calidad, se rompió rápido. No volvería a comprar.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0152', 'C022', 'P013', '2025-07-28', N'Satisface lo básico. OK.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0153', 'C024', 'P017', '2025-06-13', N'Producto llegó rápido y funciona perfecto. Muy recomendable.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0154', 'C032', 'P011', '2025-06-26', N'Muy satisfecho con la compra, lo recomiendo. Muy recomendable.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0155', 'C007', 'P010', '2024-12-18', N'Pésima atención al cliente. No volvería a comprar.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0156', 'C040', 'P011', '2025-06-27', N'Calidad superior, muy contento. Muy recomendable.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0157', 'C040', 'P006', '2025-02-01', N'Información suficiente, sin mayor novedad. OK.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0158', 'C024', 'P014', '2025-01-29', N'No funciona como esperaba, decepcionado. No volvería a comprar.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0159', 'C029', 'P010', '2025-04-08', N'Muy satisfecho con la compra, lo recomiendo. Muy recomendable.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0160', 'C024', 'P007', '2025-01-31', N'Pésima atención al cliente. No volvería a comprar.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0161', 'C025', 'P010', '2025-06-23', N'No cumple con lo anunciado, insatisfecho. No volvería a comprar.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0162', 'C009', 'P020', '2024-10-20', N'Producto recibido, cumple su función. OK.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0163', 'C036', 'P012', '2025-07-12', N'Satisface lo básico. OK.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0164', 'C011', 'P003', '2025-06-30', N'Gran relación calidad-precio. Muy recomendable.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0165', 'C015', 'P003', '2025-08-31', N'Es lo que esperaba, nada excepcional. OK.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0166', 'C026', 'P002', '2025-02-28', N'No funciona como esperaba, decepcionado. No volvería a comprar.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0167', 'C015', 'P012', '2024-09-13', N'Me encanta este producto, excelente calidad. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0168', 'C009', 'P005', '2024-09-22', N'Calidad superior, muy contento. Muy recomendable.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0169', 'C029', 'P016', '2025-09-04', N'Muy mala calidad, se rompió rápido. No volvería a comprar.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0170', 'C010', 'P007', '2024-12-17', N'Pésima atención al cliente. No volvería a comprar.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0171', 'C019', 'P004', '2025-08-20', N'Me encanta este producto, excelente calidad. Muy recomendable.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0172', 'C040', 'P014', '2025-01-01', N'Muy mala calidad, se rompió rápido. No volvería a comprar.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0173', 'C002', 'P018', '2025-05-13', N'Pésima atención al cliente. No volvería a comprar.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0174', 'C028', 'P010', '2025-05-13', N'Producto llegó rápido y funciona perfecto. Muy recomendable.', '5');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0175', 'C012', 'P014', '2024-12-19', N'Muy mala calidad, se rompió rápido. No volvería a comprar.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0176', 'C034', 'P003', '2024-12-04', N'Pésima atención al cliente. No volvería a comprar.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0177', 'C031', 'P013', '2025-03-06', N'Calidad superior, muy contento. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0178', 'C023', 'P001', '2025-05-13', N'Es lo que esperaba, nada excepcional. OK.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0179', 'C022', 'P019', '2024-12-08', N'Producto llegó rápido y funciona perfecto. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0180', 'C030', 'P006', '2024-10-25', N'Entrega correcta, sin comentarios adicionales. OK.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0181', 'C005', 'P005', '2025-08-26', N'Entrega correcta, sin comentarios adicionales. OK.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0182', 'C003', 'P007', '2025-04-05', N'Producto recibido, cumple su función. OK.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0183', 'C026', 'P017', '2025-01-14', N'Satisface lo básico. OK.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0184', 'C013', 'P002', '2024-10-13', N'Me encanta este producto, excelente calidad. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0185', 'C008', 'P009', '2025-02-21', N'Entrega correcta, sin comentarios adicionales. OK.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0186', 'C022', 'P013', '2024-09-24', N'Entrega correcta, sin comentarios adicionales. OK.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0187', 'C034', 'P012', '2025-02-08', N'Me encanta este producto, excelente calidad. Muy recomendable.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0188', 'C039', 'P014', '2024-12-08', N'Información suficiente, sin mayor novedad. OK.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0189', 'C007', 'P011', '2025-04-10', N'Producto llegó rápido y funciona perfecto. Muy recomendable.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0190', 'C028', 'P020', '2025-03-18', N'Calidad superior, muy contento. Muy recomendable.', '4');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0191', 'C023', 'P002', '2025-04-26', N'No cumple con lo anunciado, insatisfecho. No volvería a comprar.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0192', 'C026', 'P003', '2025-08-29', N'Muy satisfecho con la compra, lo recomiendo. Muy recomendable.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0193', 'C029', 'P020', '2025-05-16', N'Me encanta este producto, excelente calidad. Muy recomendable.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0194', 'C025', 'P012', '2024-11-08', N'Producto recibido, cumple su función. OK.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0195', 'C024', 'P015', '2024-11-24', N'Me encanta este producto, excelente calidad. Muy recomendable.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0196', 'C024', 'P017', '2025-05-09', N'Producto llegó rápido y funciona perfecto. Muy recomendable.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0197', 'C012', 'P001', '2024-11-30', N'No cumple con lo anunciado, insatisfecho. No volvería a comprar.', '1');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0198', 'C017', 'P009', '2024-11-04', N'Información suficiente, sin mayor novedad. OK.', '3');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0199', 'C013', 'P016', '2025-01-25', N'Me encanta este producto, excelente calidad. Muy recomendable.', '2');
INSERT INTO dbo.Resenas (IdReview, IdCliente, IdProducto, Fecha, Comentario, Rating) VALUES ('W0200', 'C006', 'P015', '2024-10-07', N'Es lo que esperaba, nada excepcional. OK.', '3');
GO
